-- Write your MySQL query statement below

SELECT A.PRODUCT_ID, 'store1' STORE, A.STORE1 price 
FROM PRODUCTS A
WHERE A.STORE1 IS NOT NULL
UNION
SELECT PRODUCT_ID, 'store2' STORE, A.STORE2 price 
FROM PRODUCTS A
WHERE A.STORE2 IS NOT NULL
UNION
SELECT PRODUCT_ID, 'store3' STORE, A.STORE3 price 
FROM PRODUCTS A 
WHERE A.STORE3 IS NOT NULL